### ISSUE TITLE
[CONFERENCE] World Conference

### ISSUE THREAD

**Issue by sleepypioneer** [PyLadiesBerlin/community-organisation#24]
**PyLadies contact:** Timna
**Conference contact:** Shir
**Conference website:**
**Conference description:**
**Does the conference pass our acceptance criteria:** *(to be fully defined but at a minimum means do they have a diverse set of speakers and DEI initiatives as well as enforced code of conduct)*

**Location:**
**Date:**
**PyLadies Attending:** Timna, tbd, tbd

## Agreement with Conference
ie what we receive as a community partner and the expectation on us.
**Tickets (number of free or discounted):** 1-3
**Advertising we will offer (ie slack/ twitter/ event page):** Not discussed but we should do a couple of social media posts to say thanks
**Additional support (ie PyLadies stand/ lunch/ CFP support):** (see below)
- **Bring your rollup/stickers giveaway** - We have dedicated a little (shared) area for our community partners in booth A78 where you can find some high tables and bar stools. There you can locate a rollup, give away some stickers to the congress attendees, and also network with other community partners :)
-  **Let's meet in person!** - I would be delighted to meet you and your team in person! I'll be all around during the congress, but I have dedicated two slots to meet you! I'll be in both congress days between 14:00-15:00 in our outdoor WeAreDevelopers Village (behind the airstream stage). So come and say hi! It would be awesome to meet in person finally! :)
- **Let's hear your voice!** - on the 2nd congress day (28/7) between 15:00-16:00, I will host a short discussion about the importance of being part of a community as a developer. It will take place at the WeAreDevelopers lounge. Will you be interested in being part of the discussion? Let me know if yes! So I'll go ahead and reserve you a sit with the panel. 

## Action steps
- [ ] ask who else wants to attend
- [ ] decide if anyone will be on the panel
- [ ] decide if you want to meet Shir when they suggested
- [ ] reply Shir's email with above
- [ ] arrange picking up banner (if you want to take it)
- [ ] ask in orga channel if anyone has a chunk of stickers to take (though right now we might favour having any we have for our events)

**Comment by tiaversa** [comment]
Event conpleted!
